FROM rpi
WORKDIR /build/linux-rpi
RUN make ARCH=arm -j$(nproc) CROSS_COMPILE=${CCPREFIX}
RUN make ARCH=arm -j$(nproc) CROSS_COMPILE=${CCPREFIX} modules
RUN make ARCH=arm CROSS_COMPILE=${CCPREFIX} INSTALL_MOD_PATH=/build/modules modules_install
WORKDIR /build/modules
RUN tar c lib | gzip >modules.tar.gz
